export const FETCH_TEAMS = 'FETCH_TEAMS';
export const GET_TEAM_ONE_BY_ID  = 'GET_TEAM_ONE_BY_ID';
export const GET_TEAM_TWO_BY_ID = 'GET_TEAM_TWO_BY_ID';
export const GET_PLAYER_ONE_BY_ID = 'GET_PLAYER_ONE_BY_ID';
export const GET_PLAYER_TWO_BY_ID = 'GET_PLAYER_TWO_BY_ID';
export const GET_CURRENTLY_COMPARING = 'GET_CuRRENTLY_COMPARING';
export const SET_CURRENTLY_COMPARING = 'SET_CuRRENTLY_COMPARING';